name: Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: postgres.dockerfile

      - name: Docker Compose Lint
        run: |
          pip install docker-compose
          docker-compose config -q
